// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_02.Models;

namespace task_02.Migrations
{
    [DbContext(typeof(BookShopDB))]
    partial class BookShopDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("task_02.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            AuthorName = "Sapkowski"
                        });
                });

            modelBuilder.Entity("task_02.Models.AuthorBookGenreMap", b =>
                {
                    b.Property<int>("AuthorBookGenreMapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("AuthorBookGenreMapID");

                    b.HasIndex("BookID");

                    b.HasIndex("GenreID");

                    b.ToTable("AuthorBookGenreMaps");

                    b.HasData(
                        new
                        {
                            AuthorBookGenreMapID = 1,
                            AuthorID = 1,
                            BookID = 2,
                            GenreID = 1
                        },
                        new
                        {
                            AuthorBookGenreMapID = 2,
                            AuthorID = 1,
                            BookID = 2,
                            GenreID = 2
                        },
                        new
                        {
                            AuthorBookGenreMapID = 3,
                            AuthorID = 1,
                            BookID = 2,
                            GenreID = 3
                        });
                });

            modelBuilder.Entity("task_02.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookYear")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = 1,
                            BookName = "Witcher:The Last Wish",
                            BookYear = 1993
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = 1,
                            BookName = "The Snake",
                            BookYear = 2009
                        });
                });

            modelBuilder.Entity("task_02.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Geners");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            GenreName = "fantasy"
                        },
                        new
                        {
                            GenreID = 2,
                            GenreName = "war film"
                        },
                        new
                        {
                            GenreID = 3,
                            GenreName = "drama"
                        });
                });

            modelBuilder.Entity("task_02.Models.AuthorBookGenreMap", b =>
                {
                    b.HasOne("task_02.Models.Book", null)
                        .WithMany("BookGenreMaps")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task_02.Models.Genre", null)
                        .WithMany("BookGenreMaps")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("task_02.Models.Book", b =>
                {
                    b.HasOne("task_02.Models.Author", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("task_02.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("task_02.Models.Book", b =>
                {
                    b.Navigation("BookGenreMaps");
                });

            modelBuilder.Entity("task_02.Models.Genre", b =>
                {
                    b.Navigation("BookGenreMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
