// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task02.Models;

namespace task02.Migrations
{
    [DbContext(typeof(BookShopDB))]
    [Migration("20210220130945_SecondBook")]
    partial class SecondBook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("task02.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            AuthorName = "Sapkowski"
                        });
                });

            modelBuilder.Entity("task02.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookYear")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = 1,
                            BookName = "The Last Wish",
                            BookYear = 1993
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = 1,
                            BookName = "The Snake",
                            BookYear = 2009
                        });
                });

            modelBuilder.Entity("task02.Models.BookGenreMap", b =>
                {
                    b.Property<int>("BookGenreMapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Book")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("BookGenreMapID");

                    b.HasIndex("BookID");

                    b.HasIndex("GenreID");

                    b.ToTable("BookGenreMaps");

                    b.HasData(
                        new
                        {
                            BookGenreMapID = 1,
                            BookID = 1,
                            GenreID = 1
                        },
                        new
                        {
                            BookGenreMapID = 2,
                            Book = "The Snake",
                            BookID = 2,
                            Genre = "fantasy",
                            GenreID = 1
                        },
                        new
                        {
                            BookGenreMapID = 3,
                            Book = "The Snake",
                            BookID = 2,
                            Genre = "war film",
                            GenreID = 2
                        });
                });

            modelBuilder.Entity("task02.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Generes");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            GenreName = "fantasy"
                        },
                        new
                        {
                            GenreID = 2,
                            GenreName = "war film"
                        });
                });

            modelBuilder.Entity("task02.Models.Book", b =>
                {
                    b.HasOne("task02.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("task02.Models.BookGenreMap", b =>
                {
                    b.HasOne("task02.Models.Book", null)
                        .WithMany("BookGenreMaps")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task02.Models.Genre", null)
                        .WithMany("BookGenreMaps")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("task02.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("task02.Models.Book", b =>
                {
                    b.Navigation("BookGenreMaps");
                });

            modelBuilder.Entity("task02.Models.Genre", b =>
                {
                    b.Navigation("BookGenreMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
