// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_03.Models;

namespace task_03.Migrations
{
    [DbContext(typeof(BookStoreDB))]
    partial class BookStoreDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("task_03.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            AuthorName = "A. Sapkowski"
                        },
                        new
                        {
                            AuthorID = 2,
                            AuthorName = "H.P. Lovecraft"
                        },
                        new
                        {
                            AuthorID = 3,
                            AuthorName = "J.K. Rowling"
                        },
                        new
                        {
                            AuthorID = 4,
                            AuthorName = "O. Wilde"
                        },
                        new
                        {
                            AuthorID = 5,
                            AuthorName = "S. King"
                        });
                });

            modelBuilder.Entity("task_03.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookYear")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = 1,
                            BookName = "Blood of Elves",
                            BookYear = 1994
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = 1,
                            BookName = "The Tower of Fools",
                            BookYear = 2002
                        },
                        new
                        {
                            BookID = 3,
                            AuthorID = 1,
                            BookName = "Sword of Destiny",
                            BookYear = 1992
                        },
                        new
                        {
                            BookID = 4,
                            AuthorID = 2,
                            BookName = "The Call of Cthulhu",
                            BookYear = 1928
                        },
                        new
                        {
                            BookID = 5,
                            AuthorID = 2,
                            BookName = "At the Mountains of Madness",
                            BookYear = 1931
                        },
                        new
                        {
                            BookID = 6,
                            AuthorID = 3,
                            BookName = "Harry Potter and Philosopher's Stone",
                            BookYear = 1997
                        },
                        new
                        {
                            BookID = 7,
                            AuthorID = 3,
                            BookName = "Harry Potter and Chamber of Secrets",
                            BookYear = 1998
                        },
                        new
                        {
                            BookID = 8,
                            AuthorID = 3,
                            BookName = "Harry Potter and Prisoner of Azkaban",
                            BookYear = 1999
                        },
                        new
                        {
                            BookID = 9,
                            AuthorID = 3,
                            BookName = "Harry Potter and Goblet of Fire",
                            BookYear = 2000
                        },
                        new
                        {
                            BookID = 10,
                            AuthorID = 3,
                            BookName = "Harry Potter and Order of the Phoenix",
                            BookYear = 2003
                        },
                        new
                        {
                            BookID = 11,
                            AuthorID = 3,
                            BookName = "Harry Potter and Half-Blood Prince",
                            BookYear = 2005
                        },
                        new
                        {
                            BookID = 12,
                            AuthorID = 3,
                            BookName = "Harry Potter and Deathly Hallows",
                            BookYear = 2007
                        },
                        new
                        {
                            BookID = 13,
                            AuthorID = 5,
                            BookName = "The Eyes of the Dragon",
                            BookYear = 1984
                        },
                        new
                        {
                            BookID = 14,
                            AuthorID = 5,
                            BookName = "Insomnia",
                            BookYear = 1994
                        },
                        new
                        {
                            BookID = 15,
                            AuthorID = 5,
                            BookName = "The Green Mile",
                            BookYear = 1996
                        },
                        new
                        {
                            BookID = 16,
                            AuthorID = 4,
                            BookName = "The Picture of Dorian Gray",
                            BookYear = 1890
                        });
                });

            modelBuilder.Entity("task_03.Models.BookGenreMap", b =>
                {
                    b.Property<int>("BookGenreMapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookID")
                        .HasColumnType("int");

                    b.Property<int?>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("BookGenreMapID");

                    b.HasIndex("BookID");

                    b.HasIndex("GenreID");

                    b.ToTable("BookGenreMaps");

                    b.HasData(
                        new
                        {
                            BookGenreMapID = 1,
                            BookID = 16,
                            GenreID = 1
                        },
                        new
                        {
                            BookGenreMapID = 2,
                            BookID = 1,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 3,
                            BookID = 3,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 4,
                            BookID = 6,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 5,
                            BookID = 7,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 6,
                            BookID = 8,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 7,
                            BookID = 9,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 8,
                            BookID = 10,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 9,
                            BookID = 11,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 10,
                            BookID = 12,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 11,
                            BookID = 13,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 12,
                            BookID = 14,
                            GenreID = 2
                        },
                        new
                        {
                            BookGenreMapID = 13,
                            BookID = 4,
                            GenreID = 3
                        },
                        new
                        {
                            BookGenreMapID = 14,
                            BookID = 5,
                            GenreID = 3
                        },
                        new
                        {
                            BookGenreMapID = 15,
                            BookID = 14,
                            GenreID = 3
                        },
                        new
                        {
                            BookGenreMapID = 16,
                            BookID = 2,
                            GenreID = 4
                        },
                        new
                        {
                            BookGenreMapID = 17,
                            BookID = 15,
                            GenreID = 5
                        },
                        new
                        {
                            BookGenreMapID = 18,
                            BookID = 15,
                            GenreID = 6
                        },
                        new
                        {
                            BookGenreMapID = 19,
                            BookID = 15,
                            GenreID = 7
                        });
                });

            modelBuilder.Entity("task_03.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            GenreName = "Philosophical fiction"
                        },
                        new
                        {
                            GenreID = 2,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            GenreID = 3,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreID = 4,
                            GenreName = "Historical fantasy"
                        },
                        new
                        {
                            GenreID = 5,
                            GenreName = "Dark Fantasy"
                        },
                        new
                        {
                            GenreID = 6,
                            GenreName = "Southern Gothic"
                        },
                        new
                        {
                            GenreID = 7,
                            GenreName = "Magic Realism"
                        });
                });

            modelBuilder.Entity("task_03.Models.Book", b =>
                {
                    b.HasOne("task_03.Models.Author", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorID");
                });

            modelBuilder.Entity("task_03.Models.BookGenreMap", b =>
                {
                    b.HasOne("task_03.Models.Book", null)
                        .WithMany("BookGenreMaps")
                        .HasForeignKey("BookID");

                    b.HasOne("task_03.Models.Genre", null)
                        .WithMany("BookGenreMaps")
                        .HasForeignKey("GenreID");
                });

            modelBuilder.Entity("task_03.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("task_03.Models.Book", b =>
                {
                    b.Navigation("BookGenreMaps");
                });

            modelBuilder.Entity("task_03.Models.Genre", b =>
                {
                    b.Navigation("BookGenreMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
